#!/usr/bin/env python3
"""Safe root-directory cleanup for the Dānā repo.

Scope was narrowed from an initial draft after checking what's actually
still referenced by live code. These are DELIBERATELY left alone because
each is either imported at runtime or is a currently-active data directory,
not legacy cruft, despite sounding like it:

  - cursor_handoffs/   — ``dana.paths.CURSOR_HANDOFF_DIR`` (== repo root,
                         since DANA_WORKSPACE == PROJECT_ROOT); the
                         delegate_to_cursor tool writes dana_handoff.md here.
  - dana_jason_loop/   — ``dana.tools.langchain_tools`` does
                         ``from dana_jason_loop.jason_critic import
                         static_code_safety_reject``.
  - start_dana.bat     — regenerated by dana.tools.setup_startup's
                         write_start_bat(), and is the actual target of the
                         Desktop's Dana.lnk shortcut.
  - stop_dana.bat / stop_dana.vbs — documented in start_dana.bat's own
                         generated comment as the shutdown step to run
                         before relaunching.

What this script actually does:
  1. Delete: fibonacci.py, .aider.chat.history.md, .aider.input.history
     (skipped if already gone).
  2. Archive into ./_offline_archive/: every *.zip at repo root,
     _archive_root_files/, legacy/.

Usage:
    python clean_repo.py            # dry run — prints the plan, changes nothing
    python clean_repo.py --apply    # actually deletes/moves
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
ARCHIVE_DIR = REPO_ROOT / "_offline_archive"

FILES_TO_DELETE = (
    "fibonacci.py",
    ".aider.chat.history.md",
    ".aider.input.history",
)

# Fixed names archived alongside every *.zip found at root (discovered by
# glob, not hardcoded, so a new backup zip added later is picked up too).
DIRS_TO_ARCHIVE = (
    "_archive_root_files",
    "legacy",
)

# Hard safety net: never touch these no matter what FILES_TO_DELETE /
# DIRS_TO_ARCHIVE end up containing after a future edit. Checked right
# before every delete/move, not just trusted by construction.
PROTECTED_NAMES = frozenset(
    {
        ".env",
        "start_dana.py",
        "start_dana.bat",
        "stop_dana.bat",
        "stop_dana.vbs",
        "dana",
        "frontend",
        "execution_jail",
        "agent_workspace",
        "freecad_output",
        "custom_tools",
        "cursor_handoffs",
        "dana_jason_loop",
    }
)


def _assert_not_protected(path: Path) -> None:
    if path.name in PROTECTED_NAMES:
        raise RuntimeError(f"refusing to touch protected path: {path}")


def _delete(path: Path, *, apply: bool) -> None:
    _assert_not_protected(path)
    if not path.exists():
        print(f"  skip (already gone): {path.name}")
        return
    print(f"  delete: {path.name}")
    if not apply:
        return
    if path.is_dir():
        shutil.rmtree(path)
    else:
        path.unlink()


def _archive(path: Path, *, apply: bool) -> None:
    _assert_not_protected(path)
    if not path.exists():
        print(f"  skip (already gone): {path.name}")
        return
    destination = ARCHIVE_DIR / path.name
    if destination.exists():
        print(f"  skip (already archived, destination exists): {path.name}")
        return
    print(f"  move: {path.name} -> _offline_archive/{path.name}")
    if not apply:
        return
    shutil.move(str(path), str(destination))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Actually perform the deletes/moves. Without this flag, only prints the plan.",
    )
    args = parser.parse_args(argv)

    mode = "APPLYING CHANGES" if args.apply else "DRY RUN (pass --apply to actually run this)"
    print(f"=== clean_repo.py — {mode} ===\n")

    print("Deleting obsolete files:")
    for name in FILES_TO_DELETE:
        _delete(REPO_ROOT / name, apply=args.apply)

    print("\nArchiving into _offline_archive/:")
    if args.apply:
        ARCHIVE_DIR.mkdir(exist_ok=True)
    zip_files = sorted(REPO_ROOT.glob("*.zip"))
    for zip_path in zip_files:
        _archive(zip_path, apply=args.apply)
    for name in DIRS_TO_ARCHIVE:
        _archive(REPO_ROOT / name, apply=args.apply)

    if not args.apply:
        print("\nNothing was changed — re-run with --apply to execute this plan.")
    else:
        print("\nDone.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
