"""Live PrusaSlicer run: a 20x20x10 mm cube sliced with the user's real
``mk4_default`` profile, and the G-code checked against that profile.

Skipped unless both exist: the PrusaSlicer CLI (``DANA_SLICER_PATH``, PATH or
the default Windows install; see slicer.find_slicer) and the exported profile
at ``agent_workspace/slicer_profiles/mk4_default.ini`` (or
``DANA_SLICER_PROFILE_DIR``). The profile is the user's own and is gitignored,
so this never runs in CI. The command-line contract is unit-tested in
tests/plugins/hardware/test_slicer.py.
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path

import pytest

from dana.plugins.hardware import slicer
from dana.plugins.os import file_system

PROFILE = slicer.DEFAULT_PROFILE
PROFILE_PATH = slicer.profile_dir() / f"{PROFILE}.ini"
SLICER = slicer.find_slicer()

pytestmark = [
    pytest.mark.e2e,
    pytest.mark.skipif(
        shutil.which(SLICER) is None and not Path(SLICER).is_file(),
        reason="PrusaSlicer CLI not found (DANA_SLICER_PATH, PATH or the default install location)",
    ),
    pytest.mark.skipif(not PROFILE_PATH.is_file(), reason=f"no exported slicer profile at {PROFILE_PATH}"),
]


def _ini_value(key: str) -> str:
    """``key``'s value in the exported profile (PrusaSlicer writes ``key = value``)."""
    m = re.search(rf"^{re.escape(key)}\s*=\s*(.*)$", PROFILE_PATH.read_text(encoding="utf-8"), re.MULTILINE)
    assert m, f"{key} missing from {PROFILE_PATH}"
    return m.group(1).strip()


@pytest.fixture
def cube_stl(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    import trimesh

    # The slicer only reads models inside the sandbox; the profile is still
    # read from its real location.
    monkeypatch.setattr(file_system, "_SANDBOX_ROOT", tmp_path)
    monkeypatch.setenv("DANA_SLICER_PROFILE_DIR", str(PROFILE_PATH.parent))
    mesh = trimesh.creation.box(extents=[20, 20, 10])
    mesh.apply_translation(-mesh.bounds[0])  # sitting on the bed at the origin
    path = tmp_path / "cube.stl"
    mesh.export(path)
    return path


def test_cube_slices_to_text_gcode_matching_the_profile(cube_stl: Path) -> None:
    result = slicer.slice_stl_to_gcode(str(cube_stl), PROFILE)

    assert result["ok"], result
    gcode = Path(result["gcode_path"])
    assert gcode.is_file() and gcode.suffix == ".gcode"
    # (Binary G-code output is refused by slice_stl_to_gcode itself.)
    text = gcode.read_text(encoding="utf-8")

    assert "generated by PrusaSlicer" in text[:500]
    # PrusaSlicer appends the full config it sliced with as '; key = value'.
    for key in ("layer_height", "filament_type", "printer_model"):
        assert f"; {key} = {_ini_value(key)}" in text, key

    # The cube is 10 mm tall: the highest layer is at 10 mm, within one layer.
    layer_z = [float(z) for z in re.findall(r"^;Z:([0-9.]+)", text, re.MULTILINE)]
    assert layer_z, "no ;Z: layer markers in the G-code"
    assert max(layer_z) == pytest.approx(10.0, abs=float(_ini_value("layer_height")))
